
nodeLinker: node-modules

npmScopes:
  mj_yu:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN}'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.8.1.cjs
